export type ElementSize = 'sm' | 'md' | 'lg'
export type ElementColor =
  | 'amber'
  | 'blue'
  | 'cyan'
  | 'fuchsia'
  | 'gray'
  | 'green'
  | 'indigo'
  | 'lime'
  | 'neutral'
  | 'orange'
  | 'pink'
  | 'purple'
  | 'red'
  | 'rose'
  | 'sky'
  | 'slate'
  | 'stone'
  | 'teal'
  | 'yellow'
  | 'zinc'

export type ElementTheme = 'dark' | 'light'
